### ISSUE TITLE
Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by francisrod01** [RNComponents/rn-spinner#7]
Hi I have a problem to start with this feature for RN.

* I just simplify my code in the screenshot for better visualization.

![image](https://user-images.githubusercontent.com/4691768/35915851-a07ddd6a-0bef-11e8-8014-8bb9dc428047.png)

# Environments

| software       | version
|--------------- | -------
| react         | 16.2.0
| react-native | 0.53.0
| rn-spinner | 0.3.2

**Comment by keithics** [comment]
this lib is outdated.. manually update it like this..

			var React = require('react')
			var ReactNative = require('react-native')
			var styles = require('./style')
			import PropTypes from 'prop-types';
			var createReactClass = require('create-react-class');

			var {
			  View,
			  Text,
			  TouchableOpacity
			} = ReactNative

			var Spinner = createReactClass({
			  propTypes: {

**Comment by francisrod01** [comment]
0.o Aah you're talking about this PR https://github.com/RNComponents/rn-spinner/pull/4 for this commit https://github.com/RNComponents/rn-spinner/pull/4/commits/403b3c7169a367db405344e1f9037802f513ec58
